### ISSUE TITLE
make requirements raises incompatibilities

### ISSUE THREAD

**Issue by dennereed** [chrisdev/wagtail-cookiecutter-foundation#996]
I get the following errors when running make requirements:

wagtail-markdown 0.5 has requirement bleach<2.2,>=1.4.2, but you'll have bleach 3.0.2 which is incompatible.
wagtail-markdown 0.5 has requirement Wagtail<2.3, but you'll have wagtail 2.4 which is incompatible.

Ignoring the errors and continuing the sequence in make develop_env, make db works, but I get errors and make migrate. The traceback looks like this:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/dnr266/Documents/pycharm/epaleo/blog/models.py", line 9, in <module>
    from wagtailmarkdown.blocks import MarkdownBlock
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/wagtailmarkdown/blocks.py", line 12, in <module>
    from .utils import render_markdown
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/wagtailmarkdown/utils.py", line 14, in <module>
    import bleach
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/bleach/__init__.py", line 5, in <module>
    from pkg_resources import parse_version
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in _build_master
    ws = cls()
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 558, in __init__
    self.add_entry(entry)
  File "/Users/dnr266/Documents/pycharm/epaleo/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 612, in add_entry
    self.entry_keys.setdefault(entry, [])
TypeError: unhashable type: 'Path'
make: *** [migrate] Error 1

The traceback references bleach, so it seems the requirement incompatibilities are causing problems and preventing the migration.

**Comment by ilendl2** [comment]
Hey thanks @dennereed. This issue has since been fixed

**Comment by mohamed-aziz** [comment]
Hi, this fixes it https://github.com/mohamed-aziz/wagtail-cookiecutter-foundation/commit/022742709938fd1aa6d7ec75ce5f61c81e9188ae
